### ISSUE TITLE
AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'

### ISSUE THREAD

**Issue by luiscastillocr** [flyingcircusio/pycountry#107]
Version 22.3.5 seems to have an issue when installing thoguth pip, found this when installing facebook-business==12.0.1 which has pycountry as a dependency

```
Python 3.6.9
pip 21.3.1
```

```Collecting pycountry>=19.8.18
  Using cached pycountry-22.3.5.tar.gz (10.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/vagrant/wikirealty/bin/python /home/vagrant/wikirealty/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp6zt7ub52
       cwd: /tmp/pip-install-4lx1lvo1/pycountry_856a01b4a1e643e78d21acf49cb2aae8
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/vagrant/wikirealty/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/vagrant/wikirealty/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/vagrant/wikirealty/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 124, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/vagrant/wikirealty/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 102, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute __legacy__```

**Comment by ctheune** [comment]
So interestingly I can't reproduce this. I used Python 3.9 with pip 21.1.3 and also tried pip-22.2.2.

**Comment by luiscastillocr** [comment]
Today i tried to upgrade from pycountry==22.1.10 to pycountry==22.3.5 and it triggered the error described above, for what is worth i had this comment in my requirements file from long ago

```
facebook-sdk==3.1.0
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# pycountry is a dependency that seems to be broken in the version 22.3.5 so we are forcing #
# the version before here before running facebook business, keep checking here to remove    #
# this pycountry fixed/forced version https://github.com/flyingcircusio/pycountry/issues/107#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
pycountry==22.1.10
facebook-business==13.0.0
```
hope this can help you to reproduce the issue
