### ISSUE TITLE
Example from README doesn't work

### ISSUE THREAD

**Issue by bpna** [flyingcircusio/pycountry#167]
```>>> pycountry.countries.search_fuzzy('England')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/patrick/country/venv/lib/python3.8/site-packages/pycountry/__init__.py", line 96, in search_fuzzy
    raise LookupError(query)
LookupError: england```

**Comment by zware** [comment]
There's an unreleased data update that enables that particular lookup.

**Comment by nschimmoller** [comment]
@bpna this has been addressed in version 23.12.7 released on PyPi please update to this version. I will be closing out this issue.
