### ISSUE TITLE
`.languages.get` fails in py2.7 as of 20.7.2

### ISSUE THREAD

**Issue by timothyaaron** [flyingcircusio/pycountry#48]
Not sure if you're still supporting python2 (I know, I know, we're working on it), but it looks like `languages.get` no longer works as of 20.7.2.

```
>>> import pycountry
>>> pycountry.languages.get(alpha_2='en')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/timothy.cloninger/.pyenv/versions/2.7.17/lib/python2.7/site-packages/pycountry/db.py", line 40, in load_if_needed
    self._load()
  File "/Users/timothy.cloninger/.pyenv/versions/2.7.17/lib/python2.7/site-packages/pycountry/db.py", line 67, in _load
    self.data_class_name, (self.data_class_base,), {})
TypeError: a new-style class can't have only classic bases
```

For now we're locked to 19.8.18, and will update as soon as the python3 migration is finished.

**Comment by ctheune** [comment]
Thanks for the report. pycountry has officially dropped support since 19.7.15, so I'm sorry but you'll have to wait for using a newer PyCountry release until you finish the migration.
