### ISSUE TITLE
pycountry.subdivisions.get(name='British Columbia') is not getting the value

### ISSUE THREAD

**Issue by rholloway4** [flyingcircusio/pycountry#93]
Trying to use this to get name, but saying KeyError, not sure why since in your steps states to input "code, name, or type".... 

exact quote
"Subdivisions can be accessed using their unique code and provide at least their code, name and type:"

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\rhollow\Python37-32\lib\site-packages\pycountry\__init__.py", line 189, in get
    subdivisions = super(Subdivisions, self).get(**kw)
  File "C:\Users\rhollow\Python37-32\lib\site-packages\pycountry\db.py", line 41, in load_if_needed
    return f(self, *args, **kw)
  File "C:\Users\rhollow\Python37-32\lib\site-packages\pycountry\db.py", line 113, in get
    index = self.indices[field]
KeyError: 'name'

**Comment by Paul-DS** [comment]
It seems you can use: `pycountry.subdivisions.lookup('British Columbia')`

**Comment by nschimmoller** [comment]
@rholloway4 the language

> Subdivisions can be accessed using their unique code and provide at least their code, name and type:

Indicates that the subdivisions can be accessed using their unique code... doing so will provide at least their code, name and type. I agree the language is a bit confusing. @Paul-DS is correct that the way to search by name is using lookup.

Going to make a quick update the README
